const leagues=[["🇬🇧","Premier League"],["🇩🇪","Bundesliga"],["🇩🇪","2. Bundesliga"],["🇪🇸","La Liga"],["🇮🇹","Serie A"],["🇫🇷","Ligue 1"],["🇳🇱","Eredivisie"],["🇵🇹","Primeira Liga"],["🇧🇪","Jupiler Pro League"],["🇨🇭","Super League"],["🇦🇹","Bundesliga Österreich"],["🇹🇷","Süper Lig"],["🇩🇰","Superliga"],["🇸🇪","Allsvenskan"],["🇳🇴","Eliteserien"],["🇭🇷","HNL"],["🇷🇸","SuperLiga"],["🇨🇿","Chance Liga"],["🇵🇱","Ekstraklasa"],["🇷🇴","Liga I"],["🇬🇷","Super League Griechenland"],["🇧🇦","Premijer Liga"],["🇷🇺","Russische Premier Liga"],["🏴","Scottish Premiership"],["🌍","WM"],["🇪🇺","EM"],["🌍","Afrika-Cup"],["🏳️","UEFA Nations League"]];
const matches=[{league:'Premier League',time:'Heute 18:30',home:'Arsenal',away:'Chelsea',odds:[1.9,3.5,3.9]},{league:'Bundesliga',time:'Heute 20:30',home:'Bayern München',away:'Borussia Dortmund',odds:[1.6,4.2,5.2]},{league:'La Liga',time:"Live 63'",home:'Real Madrid',away:'Barcelona',odds:[2.1,3.3,3.2]},{league:'Serie A',time:'Heute 20:45',home:'Inter Mailand',away:'AS Rom',odds:[1.7,3.8,4.6]},{league:'Super League',time:'Morgen 16:30',home:'FC Zürich',away:'FC Basel',odds:[2.3,3.4,2.85]},{league:'Süper Lig',time:'Morgen 19:00',home:'Galatasaray',away:'Fenerbahçe',odds:[2.25,3.25,3.05]},{league:'HNL',time:'Samstag 18:00',home:'Dinamo Zagreb',away:'Hajduk Split',odds:[1.95,3.3,3.75]},{league:'SuperLiga',time:'Sonntag 17:00',home:'Crvena zvezda',away:'Partizan',odds:[1.85,3.5,4.1]}];
let state=JSON.parse(localStorage.getItem('fwState')||'null')||{balance:1000000,user:{name:'Julian',club:''},slip:[],history:[],players:[{name:'Julian',balance:1000000},{name:'Marco',balance:875000},{name:'Leon',balance:710000}]};
const money=n=>new Intl.NumberFormat('de-CH').format(Math.round(n))+' €';
function save(){localStorage.setItem('fwState',JSON.stringify(state));renderAll()}function toast(t){let x=document.getElementById('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2000)}
function go(id){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('aside button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));scrollTo(0,0)}window.go=go;document.querySelectorAll('aside button').forEach(b=>b.onclick=()=>go(b.dataset.page));
function addBet(match,tip,odds){if(state.slip.some(x=>x.match===match)){toast('Für dieses Spiel ist schon ein Tipp gewählt.');return}state.slip.push({id:Date.now()+Math.random(),match,tip,odds});save();toast('Zum Wettschein hinzugefügt.')}window.addBet=addBet;function removeBet(id){state.slip=state.slip.filter(x=>x.id!=id);save()}window.removeBet=removeBet;
function renderLeagues(){document.getElementById('leagues').innerHTML=leagues.slice(0,6).map(x=>`<div class="league"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');document.getElementById('leagueFilter').innerHTML='<option value="all">Alle Ligen</option>'+leagues.map(x=>`<option>${x[1]}</option>`).join('')}
function renderMatches(){let f=document.getElementById('leagueFilter').value||'all',q=document.getElementById('search').value.toLowerCase();let list=matches.filter(m=>(f==='all'||m.league===f)&&(`${m.home} ${m.away} ${m.league}`.toLowerCase().includes(q)));document.getElementById('matchList').innerHTML=list.map(m=>`<div class="match"><div><small>${m.league} • ${m.time}</small><h3>${m.home} – ${m.away}</h3></div><div class="buttons"><button onclick="addBet('${m.home} – ${m.away}','1',${m.odds[0]})">1<br>${m.odds[0].toFixed(2)}</button><button onclick="addBet('${m.home} – ${m.away}','X',${m.odds[1]})">X<br>${m.odds[1].toFixed(2)}</button><button onclick="addBet('${m.home} – ${m.away}','2',${m.odds[2]})">2<br>${m.odds[2].toFixed(2)}</button></div></div>`).join('')}
document.getElementById('leagueFilter').onchange=renderMatches;document.getElementById('search').oninput=renderMatches;
function renderLive(){document.getElementById('live').innerHTML=matches.slice(0,4).map((m,i)=>`<div class="match"><div><small>${[38,45,63,20][i]}' • ${m.league}</small><h3>${m.home} – ${m.away}</h3></div><button onclick="addBet('${m.home} – ${m.away}','1',${m.odds[0]})">${m.odds[0].toFixed(2)}</button></div>`).join('')}
function totalOdds(){return state.slip.reduce((a,b)=>a*b.odds,1)}function updateWin(){let s=+document.getElementById('stake').value||0;document.getElementById('totalOdds').textContent=totalOdds().toFixed(2);document.getElementById('possibleWin').textContent=money(s*totalOdds())}document.getElementById('stake').oninput=updateWin;
function renderSlip(){document.getElementById('slip').innerHTML=state.slip.length?state.slip.map(b=>`<div class="bet"><span><b>${b.match}</b><br>Tipp ${b.tip}</span><span>${b.odds.toFixed(2)} <button onclick="removeBet('${b.id}')">×</button></span></div>`).join(''):'<p>Dein Wettschein ist leer.</p>';document.getElementById('betCount').textContent=state.slip.length;updateWin()}
document.getElementById('placeBet').onclick=()=>{let stake=+document.getElementById('stake').value;if(!state.slip.length)return toast('Wettschein ist leer.');if(stake<100)return toast('Mindesteinsatz: 100 €.');if(stake>state.balance)return toast('Nicht genügend Spielgeld.');state.balance-=stake;state.history.unshift({id:Date.now(),date:new Date().toLocaleString('de-CH'),selections:[...state.slip],stake,odds:totalOdds(),possible:stake*totalOdds(),status:'offen'});state.slip=[];save();go('history');toast('Wette gespeichert.')};
function settle(id,won){let h=state.history.find(x=>x.id===id);if(!h||h.status!=='offen')return;h.status=won?'gewonnen':'verloren';if(won)state.balance+=h.possible;save()}window.settle=settle;
function renderHistory(){document.getElementById('historyList').innerHTML=state.history.length?state.history.map(h=>`<div class="history"><div><b>${h.selections.map(s=>s.match+' ('+s.tip+')').join(', ')}</b><br><small>${h.date} • Einsatz ${money(h.stake)} • Quote ${h.odds.toFixed(2)}</small></div><div><b>${h.status.toUpperCase()}</b>${h.status==='offen'?`<br><button onclick="settle(${h.id},true)">Gewinn testen</button> <button onclick="settle(${h.id},false)">Verlust testen</button>`:''}</div></div>`).join(''):'<p>Noch keine Wetten.</p>'}
function renderRanking(){state.players[0]={name:state.user.name,balance:state.balance};document.getElementById('rankingList').innerHTML=[...state.players].sort((a,b)=>b.balance-a.balance).map((p,i)=>`<div class="rank"><b>${i+1}. ${p.name}</b><strong>${money(p.balance)}</strong></div>`).join('')}
document.getElementById('spin').onclick=()=>{let prizes=[5000,10000,25000,50000,100000,250000,500000,0],p=prizes[Math.floor(Math.random()*prizes.length)];document.getElementById('wheelDisc').style.transform=`rotate(${1440+Math.random()*360}deg)`;setTimeout(()=>{state.balance+=p;save();document.getElementById('wheelResult').textContent=p?'Gewonnen: '+money(p):'Leider eine Niete.'},4000)};
document.getElementById('saveProfile').onclick=()=>{state.user.name=document.getElementById('username').value||'Spieler';state.user.club=document.getElementById('club').value;save();toast('Profil gespeichert.')};
function renderAll(){document.getElementById('balance').textContent=money(state.balance);document.getElementById('username').value=state.user.name;document.getElementById('club').value=state.user.club;renderSlip();renderHistory();renderRanking()}renderLeagues();renderMatches();renderLive();renderAll();
